CREATE TABLE STOCK (
  STOCKNAME CHAR(50)  NOT NULL , 
  STOCKCODE CHAR(50) PRIMARY KEY);


CREATE TABLE USER (
  USERNAME CHAR(50)  PRIMARY KEY, 
  PASSWORD CHAR(50)  NOT NULL, 
  EMAIL CHAR(50) NOT NULL,
  PHONE CHAR(50));
  
  
CREATE TABLE LASTUPDATE(
  LASTUPDATETIME DATETIME PRIMARY KEY
  );

INSERT INTO Stock VALUES('通达股份','sz002560');
INSERT INTO Stock VALUES('华电国际','sh600027');
INSERT INTO Stock VALUES('国海证券','sz000750');

SELECT * FROM Stock
SELECT * FROM USER
SELECT * FROM lastupdate

ALTER  TABLE USER RENAME TO "YS"
DROP TABLE stockcode


INSERT INTO USER VALUES('test', 'test','test', 'test')

UPDATE STOCK SET STOCKNAME='江淮动力' WHERE STOCKCODE='sz000750'


DELETE  FROM stock

SELECT * FROM stock WHERE stockcode='600004'